from gan_training.models import (
    mlp,
    resnet,
    resnet_nobias,
    resnet1,
    resnet1_sigmoid,
    resnet2,
    resnet3,
    resnet4,
    resnet_proj,
    resnet_proj2,
    fastgan,
    stylegan,
    rs_haze,
    dwgan_proj,
    psmb,
    psmb_proj,
)

generator_dict = {
    'mlp1': mlp.Generator,
    'resnet': resnet.Generator,
    'resnet_nobias': resnet_nobias.Generator,
    'resnet1': resnet1.Generator,
    'resnet1_sigmoid': resnet1_sigmoid.Generator,
    'resnet2': resnet2.Generator,
    'resnet3': resnet3.Generator,
    'resnet4': resnet4.Generator,
    'resnet_proj': resnet_proj.Generator,
    'resnet_proj2': resnet_proj2.Generator,
    'fastgan': fastgan.Generator,
    'stylegan': stylegan.Generator,
    'rs_haze': rs_haze.Generator,
    'dwgan_proj': dwgan_proj.fusion_net,
    'psmb': psmb.Base_Model,
    'psmb_proj': psmb_proj.Base_Model,
}

discriminator_dict = {
    'mlp1': mlp.Discriminator,
    'resnet': resnet.Discriminator,
    'resnet_nobias': resnet_nobias.Discriminator,
    'resnet1': resnet1.Discriminator,
    'resnet1_sigmoid': resnet1_sigmoid.Discriminator,
    'resnet2': resnet2.Discriminator,
    'resnet3': resnet3.Discriminator,
    'resnet4': resnet4.Discriminator,
    'resnet_proj': resnet_proj.ProjectedDisc,
    'resnet_proj2': resnet_proj2.ProjectedDisc,
    'fastgan': fastgan.ProjectedDisc,
    'stylegan': resnet_proj2.ProjectedDisc,
    'rs_haze': rs_haze.ProjectedDisc,
    'dwgan_proj': dwgan_proj.Discriminator1,
    'psmb': psmb.Discriminator,
    'psmb_proj': psmb_proj.ProjectedDisc,
}
